services:

    zookeeper:
        image: confluentinc/cp-zookeeper
        hostname: zookeeper
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: "2181"
        volumes:
            - ./zookeeper/data:/var/lib/zookeeper/data
            - ./zookeeper/log:/var/lib/zookeeper/log
    
    kafka:
        image: confluentinc/cp-kafka
        hostname: kafka
        container_name: kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: "1"
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            KAFKA_LISTENERS: "INTERNAL://:19092,EXTERNAL://:9092"
            KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:19092,EXTERNAL://localhost:9092"
            KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
        volumes:
            - ./kafka:/var/lib/kafka/data
        depends_on:
            - zookeeper
    
    kafdrop:
        image: obsidiandynamics/kafdrop
        hostname: kafdrop
        container_name: kafdrop
        ports:
            - "9000:9000"
        environment: 
            KAFKA_BROKERCONNECT: "kafka:19092"
        depends_on:
            - kafka
