services:

    zookeeper:
        image: confluentinc/cp-zookeeper
        hostname: zookeeper
        container_name: zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: "2181"
        volumes:
            - zookeeper_data:/var/lib/zookeeper/data
            - zookeeper_log:/var/lib/zookeeper/log
        restart: unless-stopped
    
    kafka:
        image: confluentinc/cp-kafka
        hostname: kafka
        container_name: kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: "1"
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181/kafka"
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_DELETE_TOPIC_ENABLE: "true"
        volumes:
            - kafka_data:/var/lib/kafka/data
        depends_on:
            - zookeeper
        restart: unless-stopped

    cmak:
        image: hlebalbau/kafka-manager
        container_name: cmak
        ports:
            - "9000:9000"
        environment: 
            ZK_HOSTS: "zookeeper:2181"
            APPLICATION_SECRET: "random-secret"
        depends_on:
            - zookeeper
            - kafka
        restart: unless-stopped

volumes: 
    zookeeper_data:
    zookeeper_log:
    kafka_data:
