services:

    zookeeper:
        image: confluentinc/cp-zookeeper
        hostname: zookeeper
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: "2181"
        volumes:
            - ./zookeeper/data:/var/lib/zookeeper/data
            - ./zookeeper/log:/var/lib/zookeeper/log
    
    kafka_1:
        image: confluentinc/cp-kafka
        hostname: kafka_1
        container_name: kafka_1
        ports:
            - "9091:9091"
        environment:
            KAFKA_BROKER_ID: "1"
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            KAFKA_LISTENERS: "INTERNAL://:19091,EXTERNAL://:9091"
            KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka_1:19091,EXTERNAL://localhost:9091"
            KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
        volumes:
            - ./kafka_1:/var/lib/kafka/data
        depends_on:
            - zookeeper

    kafka_2:
        image: confluentinc/cp-kafka
        hostname: kafka_2
        container_name: kafka_2
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: "2"
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            KAFKA_LISTENERS: "INTERNAL://:19092,EXTERNAL://:9092"
            KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka_2:19092,EXTERNAL://localhost:9092"
            KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
        volumes:
            - ./kafka_2:/var/lib/kafka/data
        depends_on:
            - zookeeper
            
    kafka_3:
        image: confluentinc/cp-kafka
        hostname: kafka_3
        container_name: kafka_3
        ports:
            - "9093:9093"
        environment:
            KAFKA_BROKER_ID: "3"
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            KAFKA_LISTENERS: "INTERNAL://:19093,EXTERNAL://:9093"
            KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka_3:19093,EXTERNAL://localhost:9093"
            KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
        volumes:
            - ./kafka_3:/var/lib/kafka/data
        depends_on:
            - zookeeper
    
    kafdrop:
        image: obsidiandynamics/kafdrop
        hostname: kafdrop
        container_name: kafdrop
        ports:
            - "9000:9000"
        environment: 
            KAFKA_BROKERCONNECT: "kafka_1:19091,kafka_2:19092,kafka_3:19093"
        depends_on:
            - kafka_1
            - kafka_2
            - kafka_3
