services:

    zookeeper:
        image: confluentinc/cp-zookeeper
        container_name: zookeeper
        hostname: zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: "2181"
        volumes:
            - zookeeper_data:/var/lib/zookeeper/data
            - zookeeper_log:/var/lib/zookeeper/log
        restart: unless-stopped
    
    kafka:
        image: confluentinc/cp-kafka
        container_name: kafka
        hostname: kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: "1"
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181/kafka"
            KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
            KAFKA_DELETE_TOPIC_ENABLE: "true"
        volumes:
            - kafka_data:/var/lib/kafka/data
        depends_on:
            - zookeeper
        restart: unless-stopped

    schema-registry:
        image: confluentinc/cp-schema-registry
        container_name: schema-registry
        hostname: schema-registry
        ports: 
            - "8081:8081"
        environment: 
            SCHEMA_REGISTRY_HOST_NAME: "schema-registry"
            SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka:9092"
        depends_on:
            - zookeeper
            - kafka
        restart: unless-stopped

    connect:
        image: confluentinc/cp-kafka-connect
        container_name: connect
        hostname: connect
        ports:
            - "8083:8083"
        environment: 
            CONNECT_BOOTSTRAP_SERVERS: "kafka:9092"
            CONNECT_GROUP_ID: "connect-group"
            CONNECT_CONFIG_STORAGE_TOPIC: "_connect-config"
            CONNECT_OFFSET_STORAGE_TOPIC: "_connect-offset"
            CONNECT_STATUS_STORAGE_TOPIC: "_connect-status"
            CONNECT_KEY_CONVERTER: "io.confluent.connect.avro.AvroConverter"
            CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
            CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
            CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
            CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
            CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
            CONNECT_REST_ADVERTISED_HOST_NAME: "connect"
            CONNECT_PLUGIN_PATH: "/usr/share/confluent-hub-components"
        volumes: 
            - ./connectors:/usr/share/confluent-hub-components
        depends_on:
            - zookeeper
            - kafka
            - schema-registry
        restart: unless-stopped
        command: 
            - bash
            - -c
            - |
              confluent-hub install --no-prompt apache/kafka-connect-plc4x-plc4j:0.8.0
              /etc/confluent/docker/run

    cmak:
        image: hlebalbau/kafka-manager
        container_name: cmak
        ports:
            - "9000:9000"
        environment: 
            ZK_HOSTS: "zookeeper:2181"
            APPLICATION_SECRET: "random-secret"
        depends_on:
            - zookeeper
            - kafka
        restart: unless-stopped

volumes: 
    zookeeper_data:
    zookeeper_log:
    kafka_data:
